# This is a basic workflow to help you get started with Actions

name: Run tests

on:
  [ push, pull_request ]

jobs:

  tests:

    runs-on: ubuntu-latest
    strategy:

      matrix:

        python-version: [ '3.10' ]

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install -r requirements.txt
          python -m pip list

      - name: ANTLR gen
        working-directory: project/language/
        run: antlr4 FL.g4 -Dlanguage=Python3 -o dist

      - name: Run tests
        run: python ./scripts/run_tests.py
